### ISSUE TITLE
Should we use cloned `typeComposer` to keep the original one immutable?

### ISSUE THREAD

**Issue by jacobbubu** [nodkz/graphql-compose-connection#1]
According to: https://github.com/nodkz/graphql-compose-connection/blob/master/src/composeWithConnection.js#L30

We may change to
```
newTypeComposer = typeComposer.clone(newTypeName);
newTypeComposer.addResolver(resolver);
return newTypeComposer;
```

**Comment by nodkz** [comment]
Clone on `Connection` will copy only the top type and resolvers (it will not go to deeper types Edges, Node) https://github.com/nodkz/graphql-compose/blob/master/src/typeComposer.js#L258

The main purpose of `clone` method to clone single `type` for adding/removing some fields.
Widely used in copy [filters](https://github.com/nodkz/graphql-compose-mongoose/blob/4f2f1b96603d074268ff44afcfca862aa6d39c67/src/resolvers/helpers/record.js#L29) and output [records](https://github.com/nodkz/graphql-compose-mongoose/blob/4f2f1b96603d074268ff44afcfca862aa6d39c67/src/resolvers/helpers/filter.js#L64) in the graphql-compose-mongoose. Resolvers are cloned for tests, right now. And I can not imagine good business logic needs for resolver cloning.

What is your main aim (business logic) to do clone?
Immutability with types is something strange for me right now, but maybe I don't understand something.

**Comment by jacobbubu** [comment]
Thanks for the response.
There is no specific business logic for cloning. At the first sight of `composeWithConnection`, I think that is a decorator for making a higher-order `TypeComposer`.

**Comment by nodkz** [comment]
`composeWithConnection()` add one resolver `connection` to initial TypeComposer and creates proper `OutputType` for it. In other words, just extend existed TypeComposer.

On this week we will finish tests with relations between types in our big project, and I'll update https://graphql-compose-mongoose.herokuapp.com/ with a more complex example. Right now it **almost** has stable syntax.

```js
// managers.js
import mongoose from 'mongoose';
import { GraphQLString } from 'graphql';
import { CrmCompanyTC } from 'app/_schema/crm/company';
import composeWithMongoose from 'graphql-compose-mongoose';
import composeWithRelay from 'graphql-compose-relay';

const CrmManagerSchema = new mongoose.Schema({
  name: String,
  lastname: String,
  middlename: String,
  phones: [String],
  email: String,
  tags: [String],
});

CrmManagerSchema.virtual('fullname').get(function () {
  return `${this.lastname} ${this.name} ${this.middlename}`;
});

export const CrmManager = mongoose.model('CrmManager', CrmManagerSchema);
export const CrmManagerTC = composeWithRelay(composeWithMongoose(CrmManager));

CrmManagerTC.addField('fullname', {
  type: GraphQLString,
  resolve: source => source.fullname,
  projection: {
    lastname: true,
    name: true,
    middlename: true,
  },
});

CrmManagerTC.addRelation(
  'companies',
  () => ({
    resolver: CrmCompanyTC.getResolver('connection'),
    args: {
      filter: (source) => ({ managersIds: `${source._id}` }),
    },
    projection: { _id: true },
  })
);
```

```js
// company.js

import composeWithMongoose from 'graphql-compose-mongoose';
import composeWithRelay from 'graphql-compose-relay';
import mongoose from 'mongoose';
import { CrmManagerTC } from './managers';

const CrmCompanySchema = new mongoose.Schema({
  name: String,
  phones: [String],
  address: String,
  email: String,
  tags: [String],
  additionally: String,
  access: String,
  personsIds: [String],
  managersIds: [String],
});

export const CrmCompany = mongoose.model('CrmCompany', CrmCompanySchema);
export const CrmCompanyTC = composeWithRelay(composeWithMongoose(CrmCompany));

CrmCompanyTC.addRelation(
  'managers',
  () => ({
    resolver: CrmManagerTC.getResolver('findByIds'),
    args: {
      _ids: (source) => source.managersIds,
    },
    projection: { managersIds: true },
  })
);
```

Both files import each other and make cross references via the anonymous functions. That allows solve hoisting problem with `undefined`.
