### ISSUE TITLE
Got exception "regeneratorRuntime is not defined" when running in vanilla node.js without babel

### ISSUE THREAD

**Issue by jacobbubu** [nodkz/graphql-compose-connection#2]
You may need  to add "babel-plugin-transform-runtime" in `.babelrc`.

```
{
  "env": {
    "development": {
      "presets": ["es2015"],
      "plugins": [
        ...
        "transform-runtime",
      ]
    },
    "es": {
      "plugins": [
        ...
      ]
    }
  }
}
```

**Comment by nodkz** [comment]
Thanks!
All packages updated and published new versions.

Please check, and if you'll have a problem, feel free to re-open the issue.

**Comment by nodkz** [comment]
1 hour ago republish `graphql-compose` packages. Remove `transform-runtime`, fix regenerator problem for vanilla node.
